"""initial_schema

Revision ID: 7a64f709b35b
Revises: 
Create Date: 2026-06-11 13:11:05.653598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a64f709b35b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ASSUREUR', 'MEDECIN', name='roleenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('medecins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('matricule', sa.String(length=20), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('type_medecin', sa.Enum('GENERALISTE', 'SPECIALISTE', name='typemedecinenum'), nullable=False),
    sa.Column('specialite', sa.String(length=100), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medecins_matricule'), 'medecins', ['matricule'], unique=True)
    op.create_table('assures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('numero_assure', sa.String(length=20), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('date_naissance', sa.Date(), nullable=False),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('preference_paiement', sa.String(length=50), server_default='VIREMENT_BANCAIRE', nullable=False),
    sa.Column('medecin_traitant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['medecin_traitant_id'], ['medecins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assures_numero_assure'), 'assures', ['numero_assure'], unique=True)
    op.create_table('consultations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date_consultation', sa.Date(), nullable=False),
    sa.Column('motif', sa.Text(), nullable=False),
    sa.Column('diagnostic', sa.Text(), nullable=True),
    sa.Column('actes_realises', sa.Text(), nullable=True),
    sa.Column('montant_consultation', sa.Float(), nullable=False),
    sa.Column('assure_id', sa.UUID(), nullable=False),
    sa.Column('medecin_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assure_id'], ['assures.id'], ),
    sa.ForeignKeyConstraint(['medecin_id'], ['medecins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feuilles_maladie',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('statut', sa.Enum('EN_ATTENTE', 'COMPLETE', 'REMBOURSEE', name='statutfeuilleenum'), nullable=False),
    sa.Column('montant_consultation', sa.Float(), nullable=False),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('assure_id', sa.UUID(), nullable=False),
    sa.Column('consultation_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assure_id'], ['assures.id'], ),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consultation_id')
    )
    op.create_table('prescriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type_prescription', sa.Enum('MEDICAMENT', 'CONSULTATION_SPECIALISTE', name='typeprescriptionenum'), nullable=False),
    sa.Column('date_prescription', sa.DateTime(), nullable=False),
    sa.Column('consultation_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prescriptions_consultation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('motif', sa.Text(), nullable=False),
    sa.Column('specialiste_id', sa.UUID(), nullable=True),
    sa.Column('prescription_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
    sa.ForeignKeyConstraint(['specialiste_id'], ['medecins.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prescription_id')
    )
    op.create_table('prescriptions_medicament',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom_medicament', sa.String(length=200), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('posologie', sa.Text(), nullable=False),
    sa.Column('duree_traitement_jours', sa.Integer(), nullable=False),
    sa.Column('prescription_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prescription_id')
    )
    op.create_table('remboursements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('taux_remboursement', sa.Float(), nullable=False),
    sa.Column('montant_consultation', sa.Float(), nullable=False),
    sa.Column('montant_rembourse', sa.Float(), nullable=False),
    sa.Column('mode_paiement', sa.Enum('VIREMENT_BANCAIRE', 'ESPECES', name='modepaiementenum'), nullable=False),
    sa.Column('statut', sa.Enum('EN_ATTENTE', 'PAYE', 'ANNULE', name='statutremboursementenum'), nullable=False),
    sa.Column('reference_virement', sa.String(length=100), nullable=True),
    sa.Column('facture_path', sa.String(length=500), nullable=True),
    sa.Column('assure_id', sa.UUID(), nullable=False),
    sa.Column('feuille_maladie_id', sa.UUID(), nullable=False),
    sa.Column('date_remboursement', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assure_id'], ['assures.id'], ),
    sa.ForeignKeyConstraint(['feuille_maladie_id'], ['feuilles_maladie.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feuille_maladie_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('remboursements')
    op.drop_table('prescriptions_medicament')
    op.drop_table('prescriptions_consultation')
    op.drop_table('prescriptions')
    op.drop_table('feuilles_maladie')
    op.drop_table('consultations')
    op.drop_index(op.f('ix_assures_numero_assure'), table_name='assures')
    op.drop_table('assures')
    op.drop_index(op.f('ix_medecins_matricule'), table_name='medecins')
    op.drop_table('medecins')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
